### **Example 1**

In [134]:
# create model class
import torch
import torch.nn as nn

class Model(nn.Module):
  def __init__(self, num_features):
    super().__init__()
    self.linear = nn.Linear(num_features, 1)
    self.sigmoid = nn.Sigmoid()

  def forward(self, features):
    out = self.linear(features)
    out = self.sigmoid(out)

    return out

In [135]:
# create dataset
features = torch.rand(10, 5)

# create model
model = Model(features.shape[1])

# call model for forward pass
# model.forward(features)
model(features)

tensor([[0.6428],
        [0.6792],
        [0.7250],
        [0.6552],
        [0.6406],
        [0.6248],
        [0.6631],
        [0.6388],
        [0.6573],
        [0.6537]], grad_fn=<SigmoidBackward0>)

In [136]:
# show model weights
model.linear.weight

Parameter containing:
tensor([[0.2145, 0.2617, 0.2958, 0.4056, 0.3604]], requires_grad=True)

In [137]:
# show model bias
model.linear.bias

Parameter containing:
tensor([-0.1133], requires_grad=True)

In [138]:
!pip install torchinfo

In [139]:
from torchinfo import summary

summary(model, input_size=(10, 5))

Layer (type:depth-idx)                   Output Shape              Param #
Model                                    [10, 1]                   --
├─Linear: 1-1                            [10, 1]                   6
├─Sigmoid: 1-2                           [10, 1]                   --
Total params: 6
Trainable params: 6
Non-trainable params: 0
Total mult-adds (M): 0.00
Input size (MB): 0.00
Forward/backward pass size (MB): 0.00
Params size (MB): 0.00
Estimated Total Size (MB): 0.00

### **Example 2**

In [140]:
# create model class
import torch
import torch.nn as nn

class Model(nn.Module):
  def __init__(self, num_features):
    super().__init__()
    self.linear1 = nn.Linear(num_features, 3)
    self.relu = nn.ReLU()
    self.linear2 = nn.Linear(3, 1)
    self.sigmoid = nn.Sigmoid()

  def forward(self, features):
    out = self.linear1(features)
    out = self.relu(out)
    out = self.linear2(out)
    out = self.sigmoid(out)

    return out

In [141]:
# create dataset
features = torch.rand(10, 5)

# create model
model = Model(features.shape[1])

# call model for forward pass
# model.forward(features)
model(features)

tensor([[0.4574],
        [0.4574],
        [0.4574],
        [0.4574],
        [0.4574],
        [0.4574],
        [0.4574],
        [0.4574],
        [0.4574],
        [0.4574]], grad_fn=<SigmoidBackward0>)

In [142]:
# show model weights
print(model.linear1.weight)
print(model.linear2.weight)

Parameter containing:
tensor([[-0.1481, -0.0915, -0.4236,  0.3163, -0.0888],
        [-0.2502, -0.2078, -0.0118, -0.2649, -0.2500],
        [-0.0792,  0.0572, -0.4009, -0.4037, -0.2170]], requires_grad=True)
Parameter containing:
tensor([[-0.3615, -0.3172, -0.1661]], requires_grad=True)


In [143]:
from torchinfo import summary

summary(model, input_size=(10, 5))

Layer (type:depth-idx)                   Output Shape              Param #
Model                                    [10, 1]                   --
├─Linear: 1-1                            [10, 3]                   18
├─ReLU: 1-2                              [10, 3]                   --
├─Linear: 1-3                            [10, 1]                   4
├─Sigmoid: 1-4                           [10, 1]                   --
Total params: 22
Trainable params: 22
Non-trainable params: 0
Total mult-adds (M): 0.00
Input size (MB): 0.00
Forward/backward pass size (MB): 0.00
Params size (MB): 0.00
Estimated Total Size (MB): 0.00

### **Example 3: Using concept of Sequential Containers**

In [144]:
# create model class
import torch
import torch.nn as nn

class Model(nn.Module):
  def __init__(self, num_features):
    super().__init__()
    self.network = nn.Sequential(
        nn.Linear(num_features, 3),
        nn.ReLU(),
        nn.Linear(3, 1),
        nn.Sigmoid()
    )

  def forward(self, features):
    out = self.network(features)

    return out

In [145]:
# create dataset
features = torch.rand(10, 5)

# create model
model = Model(features.shape[1])

# call model for forward pass
# model.forward(features)
model(features)

tensor([[0.5515],
        [0.5492],
        [0.5492],
        [0.5492],
        [0.5492],
        [0.5518],
        [0.5492],
        [0.5492],
        [0.5492],
        [0.5492]], grad_fn=<SigmoidBackward0>)

### **Using nn Module on Real World Dataset**

In [146]:
import pandas as pd
import numpy as np
import torch
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder

### **Exploring data**

In [147]:
df = pd.read_csv('https://raw.githubusercontent.com/gscdit/Breast-Cancer-Detection/refs/heads/master/data.csv')
df.head()

id diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0    842302         M        17.99         10.38          122.80     1001.0   
1    842517         M        20.57         17.77          132.90     1326.0   
2  84300903         M        19.69         21.25          130.00     1203.0   
3  84348301         M        11.42         20.38           77.58      386.1   
4  84358402         M        20.29         14.34          135.10     1297.0   

   smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0          0.11840           0.27760          0.3001              0.14710   
1          0.08474           0.07864          0.0869              0.07017   
2          0.10960           0.15990          0.1974              0.12790   
3          0.14250           0.28390          0.2414              0.10520   
4          0.10030           0.13280          0.1980              0.10430   

   ...  texture_worst  perimeter_worst  area_worst  smoothness_worst  \
0  ...          17.33           184.60      2019.0            0.1622   
1  ...          23.41           158.80      1956.0            0.1238   
2  ...          25.53           152.50      1709.0            0.1444   
3  ...          26.50            98.87       567.7            0.2098   
4  ...          16.67           152.20      1575.0            0.1374   

   compactness_worst  concavity_worst  concave points_worst  symmetry_worst  \
0             0.6656           0.7119                0.2654          0.4601   
1             0.1866           0.2416                0.1860          0.2750   
2             0.4245           0.4504                0.2430          0.3613   
3             0.8663           0.6869                0.2575          0.6638   
4             0.2050           0.4000                0.1625          0.2364   

   fractal_dimension_worst  Unnamed: 32  
0                  0.11890          NaN  
1                  0.08902          NaN  
2                  0.08758          NaN  
3                  0.17300          NaN  
4                  0.07678          NaN  

[5 rows x 33 columns]

In [148]:
df.shape

(569, 33)

In [149]:
df.drop(columns=['id', 'Unnamed: 32'], inplace=True)

In [150]:
df.head()

diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0         M        17.99         10.38          122.80     1001.0   
1         M        20.57         17.77          132.90     1326.0   
2         M        19.69         21.25          130.00     1203.0   
3         M        11.42         20.38           77.58      386.1   
4         M        20.29         14.34          135.10     1297.0   

   smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0          0.11840           0.27760          0.3001              0.14710   
1          0.08474           0.07864          0.0869              0.07017   
2          0.10960           0.15990          0.1974              0.12790   
3          0.14250           0.28390          0.2414              0.10520   
4          0.10030           0.13280          0.1980              0.10430   

   symmetry_mean  ...  radius_worst  texture_worst  perimeter_worst  \
0         0.2419  ...         25.38          17.33           184.60   
1         0.1812  ...         24.99          23.41           158.80   
2         0.2069  ...         23.57          25.53           152.50   
3         0.2597  ...         14.91          26.50            98.87   
4         0.1809  ...         22.54          16.67           152.20   

   area_worst  smoothness_worst  compactness_worst  concavity_worst  \
0      2019.0            0.1622             0.6656           0.7119   
1      1956.0            0.1238             0.1866           0.2416   
2      1709.0            0.1444             0.4245           0.4504   
3       567.7            0.2098             0.8663           0.6869   
4      1575.0            0.1374             0.2050           0.4000   

   concave points_worst  symmetry_worst  fractal_dimension_worst  
0                0.2654          0.4601                  0.11890  
1                0.1860          0.2750                  0.08902  
2                0.2430          0.3613                  0.08758  
3                0.2575          0.6638                  0.17300  
4                0.1625          0.2364                  0.07678  

[5 rows x 31 columns]

### **Train test split**

In [151]:
X_train, X_test, y_train, y_test = train_test_split(df.iloc[:, 1:], df.iloc[:, 0], test_size=0.2)

### **Scaling**

In [152]:
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [153]:
X_train

array([[ 1.29812573,  0.13891271,  1.16460719, ...,  0.23901827,
        -0.55488108, -1.53477507],
       [-0.20174021,  0.26270979, -0.13352303, ...,  1.38194183,
         1.16061329,  1.60119317],
       [ 1.04861014,  0.37733671,  1.30544587, ...,  1.25058866,
         0.58765839,  2.12258524],
       ...,
       [ 0.6466128 ,  0.16871571,  0.69782757, ...,  1.35778492,
         0.26579256,  0.6808483 ],
       [-1.22198174, -0.26457405, -1.25661089, ..., -1.7146714 ,
        -1.66371732, -1.0532197 ],
       [ 1.70844026, -1.15407896,  1.73600983, ...,  0.73876424,
        -0.89696886, -0.3976717 ]])

In [154]:
y_train

277    M
512    M
400    M
548    B
291    B
      ..
163    B
1      M
177    M
192    B
4      M
Name: diagnosis, Length: 455, dtype: object

### **Label Encoding**

In [155]:
encoder = LabelEncoder()
y_train = encoder.fit_transform(y_train)
y_test = encoder.transform(y_test)

In [156]:
y_train

array([1, 1, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0,
       1, 1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1,
       1, 0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1,
       1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0,
       0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0,
       1, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 0, 1, 1, 1, 0, 1, 1, 0, 0, 0, 1, 0,
       0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1,
       0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0,
       1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1,
       0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 1,
       0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 1, 1, 1, 0, 0,

### **Numpy arrays to PyTorch Tensors**

In [157]:
X_train_tensor = torch.from_numpy(X_train)
X_test_tensor = torch.from_numpy(X_test)
y_train_tensor = torch.from_numpy(y_train)
y_test_tensor = torch.from_numpy(y_test)

In [158]:
X_train_tensor.shape

torch.Size([455, 30])

In [159]:
y_train_tensor.shape

torch.Size([455])

### **Defining the model**

In [160]:
import torch.nn as nn
import torch.optim as optimizer

class MySimpleNN(nn.Module):

  def __init__(self, num_features):
    super().__init__()
    self.linear = nn.Linear(num_features, 1)
    self.sigmoid = nn.Sigmoid()

  def forward(self, features):
    out = self.linear(features)
    out = self.sigmoid(out)
    return out

### **Important Parameters**

In [161]:
learning_rate = 0.1
epochs = 25

In [162]:
# define loss function
loss_function = nn.BCELoss()

### **Training Pipeline**

In [163]:
# create model
model = MySimpleNN(X_train_tensor.shape[1])

# define optimizer
optimizer = torch.optim.SGD(model.parameters(), lr=learning_rate)

# Change the data type of the model's parameters to match the input tensor
model.linear.weight = nn.Parameter(model.linear.weight.type(X_train_tensor.dtype))
model.linear.bias = nn.Parameter(model.linear.bias.type(X_train_tensor.dtype))

# define loop
for epoch in range(epochs):
  # forward pass
  y_pred = model(X_train_tensor)

  # loss calculate
  loss = loss_function(y_pred, y_train_tensor.view(-1, 1).type(torch.float64))

  # clear gradients
  optimizer.zero_grad()

  # backward pass
  loss.backward()

  # parameters update
  optimizer.step()

  # print loss in each epoch
  print(f'Epoch: {epoch+1}, Loss: {loss.item()}')

Epoch: 1, Loss: 0.7022646288372901
Epoch: 2, Loss: 0.7022646288372901
Epoch: 3, Loss: 0.7022646288372901
Epoch: 4, Loss: 0.7022646288372901
Epoch: 5, Loss: 0.7022646288372901
Epoch: 6, Loss: 0.7022646288372901
Epoch: 7, Loss: 0.7022646288372901
Epoch: 8, Loss: 0.7022646288372901
Epoch: 9, Loss: 0.7022646288372901
Epoch: 10, Loss: 0.7022646288372901
Epoch: 11, Loss: 0.7022646288372901
Epoch: 12, Loss: 0.7022646288372901
Epoch: 13, Loss: 0.7022646288372901
Epoch: 14, Loss: 0.7022646288372901
Epoch: 15, Loss: 0.7022646288372901
Epoch: 16, Loss: 0.7022646288372901
Epoch: 17, Loss: 0.7022646288372901
Epoch: 18, Loss: 0.7022646288372901
Epoch: 19, Loss: 0.7022646288372901
Epoch: 20, Loss: 0.7022646288372901
Epoch: 21, Loss: 0.7022646288372901
Epoch: 22, Loss: 0.7022646288372901
Epoch: 23, Loss: 0.7022646288372901
Epoch: 24, Loss: 0.7022646288372901
Epoch: 25, Loss: 0.7022646288372901


In [164]:
model.linear.weight

Parameter containing:
tensor([[ 0.1783,  0.0475,  0.1264, -0.1145,  0.0650, -0.0469, -0.1175,  0.1203,
         -0.1320,  0.0534, -0.0500,  0.0303, -0.1291,  0.1135,  0.0971,  0.0076,
         -0.0088, -0.0358,  0.0849, -0.0320,  0.0157,  0.1523, -0.0999,  0.0902,
         -0.0428, -0.1333,  0.0855,  0.0939, -0.1810, -0.1356]],
       dtype=torch.float64, requires_grad=True)

In [165]:
model.linear.bias

Parameter containing:
tensor([0.0576], dtype=torch.float64, requires_grad=True)

### **Evaluation**

In [166]:
# model evaluation
with torch.no_grad():
  y_pred = model.forward(X_test_tensor)
  y_pred = (y_pred > 0.5).float()
  accuracy = (y_pred == y_test_tensor).float().mean()
  print(f'Accuracy: {accuracy.item()}')

Accuracy: 0.4853801131248474
