# **Tensors in PyTorch**

In [1]:
import torch
print(torch.__version__)

2.5.1+cu121


In [2]:
if torch.cuda.is_available():
  print("GPU is available!")
  print(f"Using GPU: {torch.cuda.get_device_name(0)}")
else:
  print("GPU is not available. Using CPU.")

GPU is available!
Using GPU: Tesla T4


### **1. Creating a Tensor**

In [3]:
# using empty
a = torch.empty(2, 3)
print(a)

tensor([[0., 0., 0.],
        [0., 0., 0.]])


In [4]:
# check type
type(a)

torch.Tensor

In [5]:
# using zeros
torch.zeros(2, 3)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [6]:
# using ones
torch.ones(2, 3)

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [7]:
# using rand
torch.rand(2, 3)

tensor([[7.0935e-01, 6.6269e-01, 6.7580e-04],
        [3.0836e-01, 1.2692e-01, 9.0312e-01]])

In [8]:
# use of manual seed
torch.manual_seed(100)
torch.rand(2, 3)

tensor([[0.1117, 0.8158, 0.2626],
        [0.4839, 0.6765, 0.7539]])

In [9]:
# using tensor
torch.tensor([[1, 2, 3], [4, 5, 6]])

tensor([[1, 2, 3],
        [4, 5, 6]])

In [10]:
# other ways

# arange
print("Using arange: ", torch.arange(0, 10, 2))

# linspace
print("Using linspace: ", torch.linspace(0, 10, 10))

# eye
print("Using eye: ", torch.eye(5))

# full
print("Using full: ", torch.full((3, 3), 5))

Using arange:  tensor([0, 2, 4, 6, 8])
Using linspace:  tensor([ 0.0000,  1.1111,  2.2222,  3.3333,  4.4444,  5.5556,  6.6667,  7.7778,
         8.8889, 10.0000])
Using eye:  tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])
Using full:  tensor([[5, 5, 5],
        [5, 5, 5],
        [5, 5, 5]])


### **2. Tensor Shapes**

In [11]:
x = torch.tensor([[1, 2, 3], [4, 5, 6]])
print("Tensor x: ", x)
print("Shape of x: ", x.shape)

Tensor x:  tensor([[1, 2, 3],
        [4, 5, 6]])
Shape of x:  torch.Size([2, 3])


In [12]:
# It is used when we have to create a tensor of the same shape as x shape
torch.empty_like(x)

tensor([[4122587173771174241, 6874590268765514786, 2459029315949459828],
        [6874028453778520165, 2318265813094655346, 7881702260482471202]])

In [13]:
# It is used when we have to create a tensor of the same shape as x shape
torch.zeros_like(x)

tensor([[0, 0, 0],
        [0, 0, 0]])

In [14]:
# It is used when we have to create a tensor of the same shape as x shape
torch.ones_like(x)

tensor([[1, 1, 1],
        [1, 1, 1]])

In [15]:
# torch.rand_like(x)

# Above command won't work as the datatype of x elements is int and the rand or rand_like generate numbers of float datatype.

## Solution for above command

torch.rand_like(x, dtype=torch.float32)

tensor([[0.2627, 0.0428, 0.2080],
        [0.1180, 0.1217, 0.7356]])

### **3. Tensor Data Types**

In [16]:
# find data type
x.dtype

torch.int64

In [17]:
# assign data type
torch.tensor([1.0, 2.0, 3.0], dtype=torch.int32)

tensor([1, 2, 3], dtype=torch.int32)

In [18]:
torch.tensor([1, 2, 3], dtype=torch.float64)

tensor([1., 2., 3.], dtype=torch.float64)

In [19]:
# using to()
x.to(torch.float32)

tensor([[1., 2., 3.],
        [4., 5., 6.]])

### **4. Mathematical Operations**

In [20]:
# Scalar operation
x = torch.rand(2, 2)
x

tensor([[0.7118, 0.7876],
        [0.4183, 0.9014]])

In [21]:
# addition
add = x + 2

print(add)

tensor([[2.7118, 2.7876],
        [2.4183, 2.9014]])


In [22]:
# subtration
sub = x - 2

print(sub)

tensor([[-1.2882, -1.2124],
        [-1.5817, -1.0986]])


In [23]:
# multiplication
mul = x * 2

print(mul)

tensor([[1.4235, 1.5752],
        [0.8366, 1.8028]])


In [24]:
# division
div = x / 2

print(div)

tensor([[0.3559, 0.3938],
        [0.2092, 0.4507]])


In [25]:
# integer division
int_div = (x*100) // 2

print(int_div)

tensor([[35., 39.],
        [20., 45.]])


In [26]:
# mod
mod = (x*100) % 2

print(mod)

tensor([[1.1765, 0.7581],
        [1.8305, 0.1415]])


In [27]:
# power
power = x**2

print(power)

tensor([[0.5066, 0.6203],
        [0.1750, 0.8125]])


### **5. Element wise operations**

In [28]:
a = torch.rand(2, 3)
b = torch.rand(2, 3)

print(a)
print(b)

tensor([[0.9969, 0.7565, 0.2239],
        [0.3023, 0.1784, 0.8238]])
tensor([[0.5557, 0.9770, 0.4440],
        [0.9478, 0.7445, 0.4892]])


In [29]:
# add
add = a + b

print(add)

tensor([[1.5526, 1.7335, 0.6679],
        [1.2502, 0.9229, 1.3130]])


In [30]:
# sub
sub = a - b

print(sub)

tensor([[ 0.4411, -0.2205, -0.2201],
        [-0.6455, -0.5661,  0.3346]])


In [31]:
# mul
mul = a * b

print(mul)

tensor([[0.5540, 0.7391, 0.0994],
        [0.2866, 0.1328, 0.4030]])


In [32]:
# div
div = a / b

print(div)

tensor([[1.7938, 0.7743, 0.5042],
        [0.3190, 0.2397, 1.6841]])


In [33]:
# power
power = a**b

print(power)

tensor([[0.9983, 0.7614, 0.5145],
        [0.3218, 0.2771, 0.9096]])


In [34]:
# mod
mod = a % b

print(mod)

tensor([[0.4411, 0.7565, 0.2239],
        [0.3023, 0.1784, 0.3346]])


In [35]:
c = torch.tensor([1, -2, 3, -4])

In [36]:
# abs
abs = torch.abs(c)

print(abs)

tensor([1, 2, 3, 4])


In [37]:
# negative
neg = torch.neg(c)

print(neg)

tensor([-1,  2, -3,  4])


In [38]:
d = torch.tensor([1.9, 2.3, 3.7, 4.4])

In [39]:
# round
round = torch.round(d)

print(round)

tensor([2., 2., 4., 4.])


In [40]:
# ceil
ceil = torch.ceil(d)

print(ceil)

tensor([2., 3., 4., 5.])


In [41]:
# floor
floor = torch.floor(d)

print(floor)

tensor([1., 2., 3., 4.])


In [42]:
# clamp
clamp = torch.clamp(d, min=2, max=3)

print(clamp)

tensor([2.0000, 2.3000, 3.0000, 3.0000])


### **6. Reduction operation**

In [47]:
e = torch.randint(size=(2, 3), low=0, high=10, dtype=torch.float32)
e

tensor([[5., 7., 3.],
        [9., 4., 0.]])

In [48]:
# sum
torch.sum(e)

tensor(28.)

In [49]:
# sum along columns
torch.sum(e, dim=0)

tensor([14., 11.,  3.])

In [50]:
# sum along rows
torch.sum(e, dim=1)

tensor([15., 13.])

In [51]:
# mean
torch.mean(e)

tensor(4.6667)

In [52]:
# mean along col
torch.mean(e, dim=0)

tensor([7.0000, 5.5000, 1.5000])

In [53]:
# median
torch.median(e)

tensor(4.)

In [54]:
# max
torch.max(e)

tensor(9.)

In [55]:
# min
torch.min(e)

tensor(0.)

In [56]:
# product
torch.prod(e)

tensor(0.)

In [57]:
# standard deviation
torch.std(e)

tensor(3.1411)

In [58]:
# variance
torch.var(e)

tensor(9.8667)

In [59]:
# argmax
torch.argmax(e)

tensor(3)

In [60]:
# argmin
torch.argmin(e)

tensor(5)

### **7. Matrix operations**

In [61]:
f = torch.randint(size=(2, 3), low=0, high=10)
g = torch.randint(size=(3, 2), low=0, high=10)

print(f)
print(g)

tensor([[5, 7, 5],
        [9, 9, 7]])
tensor([[5, 9],
        [8, 9],
        [7, 9]])


In [62]:
# matrix multiplication
torch.matmul(f, g)

tensor([[116, 153],
        [166, 225]])

In [63]:
vector1 = torch.tensor([1, 2])
vector2 = torch.tensor([3, 4])

# dot product
torch.dot(vector1, vector2)

tensor(11)

In [64]:
# transpose
torch.transpose(f, 0, 1)

tensor([[5, 9],
        [7, 9],
        [5, 7]])

In [65]:
h = torch.randint(size=(3, 3), low=0, high=10, dtype=torch.float32)
h

tensor([[2., 6., 7.],
        [7., 8., 3.],
        [6., 1., 5.]])

In [66]:
# determinant
torch.det(h)

tensor(-315.)

In [67]:
# inverse
torch.inverse(h)

tensor([[-0.1175,  0.0730,  0.1206],
        [ 0.0540,  0.1016, -0.1365],
        [ 0.1302, -0.1079,  0.0825]])

### **8. Comparison Operations**

In [68]:
i = torch.randint(size=(2, 3), low=0, high=10)
j = torch.randint(size=(2, 3), low=0, high=10)

print(i)
print(j)

tensor([[5, 0, 4],
        [3, 8, 8]])
tensor([[3, 3, 5],
        [0, 6, 4]])


In [69]:
# greater than
i > j

tensor([[ True, False, False],
        [ True,  True,  True]])

In [70]:
# less than
i < j

tensor([[False,  True,  True],
        [False, False, False]])

In [71]:
# equal to
i == j

tensor([[False, False, False],
        [False, False, False]])

In [72]:
# not equal to
i != j

tensor([[True, True, True],
        [True, True, True]])

In [73]:
# greater than equal to
i >= j

tensor([[ True, False, False],
        [ True,  True,  True]])

In [74]:
# less than equal to
i <= j

tensor([[False,  True,  True],
        [False, False, False]])

### **9. Special Functions**

In [81]:
k = torch.randint(size=(2, 3), low=0, high=10, dtype=torch.float32)
k

tensor([[8., 5., 6.],
        [2., 9., 5.]])

In [82]:
# log
torch.log(k)

tensor([[2.0794, 1.6094, 1.7918],
        [0.6931, 2.1972, 1.6094]])

In [83]:
# exp
torch.exp(k)

tensor([[2.9810e+03, 1.4841e+02, 4.0343e+02],
        [7.3891e+00, 8.1031e+03, 1.4841e+02]])

In [84]:
# sqrt
torch.sqrt(k)

tensor([[2.8284, 2.2361, 2.4495],
        [1.4142, 3.0000, 2.2361]])

In [85]:
# sigmoid
torch.sigmoid(k)

tensor([[0.9997, 0.9933, 0.9975],
        [0.8808, 0.9999, 0.9933]])

In [86]:
# softmax
torch.softmax(k, dim=0)

tensor([[0.9975, 0.0180, 0.7311],
        [0.0025, 0.9820, 0.2689]])

In [87]:
# relu
torch.relu(k)

tensor([[8., 5., 6.],
        [2., 9., 5.]])

### **10. Inplace Operations**

In [88]:
m = torch.rand(2, 3)
n = torch.rand(2, 3)

print(m)
print(n)

tensor([[0.2855, 0.2324, 0.9141],
        [0.7668, 0.1659, 0.4393]])
tensor([[0.2243, 0.8935, 0.0497],
        [0.1780, 0.3011, 0.1893]])


In [89]:
m.add_(n)

tensor([[0.5098, 1.1259, 0.9638],
        [0.9448, 0.4670, 0.6286]])

In [90]:
m

tensor([[0.5098, 1.1259, 0.9638],
        [0.9448, 0.4670, 0.6286]])

In [91]:
torch.relu(m)

tensor([[0.5098, 1.1259, 0.9638],
        [0.9448, 0.4670, 0.6286]])

In [92]:
m.relu_()

tensor([[0.5098, 1.1259, 0.9638],
        [0.9448, 0.4670, 0.6286]])

In [93]:
m

tensor([[0.5098, 1.1259, 0.9638],
        [0.9448, 0.4670, 0.6286]])

### **11. Copying a Tensor**

In [94]:
a = torch.rand(2, 3)
a

tensor([[0.9186, 0.2131, 0.3957],
        [0.6017, 0.4234, 0.5224]])

In [95]:
b = a
b

tensor([[0.9186, 0.2131, 0.3957],
        [0.6017, 0.4234, 0.5224]])

In [96]:
a[0][0] = 0.0
print(a)

tensor([[0.0000, 0.2131, 0.3957],
        [0.6017, 0.4234, 0.5224]])


In [99]:
print(b)

tensor([[0.0000, 0.2131, 0.3957],
        [0.6017, 0.4234, 0.5224]])


In [97]:
id(a)

138250507235584

In [98]:
id(b)

138250507235584

In [100]:
b = a.clone()
b

tensor([[0.0000, 0.2131, 0.3957],
        [0.6017, 0.4234, 0.5224]])

In [101]:
a[0][0] = 1.0
a

tensor([[1.0000, 0.2131, 0.3957],
        [0.6017, 0.4234, 0.5224]])

In [102]:
b

tensor([[0.0000, 0.2131, 0.3957],
        [0.6017, 0.4234, 0.5224]])

In [103]:
id(a)

138250507235584

In [104]:
id(b)

138250506944112

### **12. Tensor Operations on GPU**

In [105]:
torch.cuda.is_available()

True

In [106]:
device = torch.device('cuda')

In [107]:
# creating a new tensor on GPU
torch.rand((2, 3), device=device)

tensor([[0.3563, 0.0303, 0.7088],
        [0.2009, 0.0224, 0.9896]], device='cuda:0')

In [108]:
# moving an existing tensor to GPU
a = torch.rand(2, 3)
a

tensor([[0.4175, 0.0340, 0.9157],
        [0.3079, 0.6269, 0.8277]])

In [111]:
b = a.to(device)

In [112]:
b + 5

tensor([[5.4175, 5.0340, 5.9157],
        [5.3079, 5.6269, 5.8277]], device='cuda:0')

### **13. Reshaping Tensors**

In [113]:
a = torch.ones(4, 4)
a

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [114]:
# reshape
a.reshape(2, 2, 2, 2)

tensor([[[[1., 1.],
          [1., 1.]],

         [[1., 1.],
          [1., 1.]]],


        [[[1., 1.],
          [1., 1.]],

         [[1., 1.],
          [1., 1.]]]])

In [115]:
# flatten
a.flatten()

tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [116]:
b = torch.rand(2, 3, 4)
b

tensor([[[0.6594, 0.0887, 0.4890, 0.5887],
         [0.7340, 0.8497, 0.9112, 0.4847],
         [0.9436, 0.3904, 0.2499, 0.3206]],

        [[0.9753, 0.7582, 0.6688, 0.2651],
         [0.2336, 0.5057, 0.5688, 0.0634],
         [0.8993, 0.2732, 0.3397, 0.1879]]])

In [117]:
# permute
b.permute(2, 0, 1)

tensor([[[0.6594, 0.7340, 0.9436],
         [0.9753, 0.2336, 0.8993]],

        [[0.0887, 0.8497, 0.3904],
         [0.7582, 0.5057, 0.2732]],

        [[0.4890, 0.9112, 0.2499],
         [0.6688, 0.5688, 0.3397]],

        [[0.5887, 0.4847, 0.3206],
         [0.2651, 0.0634, 0.1879]]])

In [118]:
# unsqueeze
# image size
c = torch.rand(226, 226, 3)
c.unsqueeze(0).shape

torch.Size([1, 226, 226, 3])

In [119]:
# squeeze
d = torch.rand(1, 20)
d.squeeze(0)

tensor([0.7936, 0.2313, 0.6106, 0.0260, 0.9428, 0.8335, 0.6601, 0.2328, 0.9062,
        0.9867, 0.5495, 0.1893, 0.8159, 0.7631, 0.0105, 0.1216, 0.4416, 0.8206,
        0.5347, 0.8359])

### **14. Numpy and PyTorch**

In [120]:
import numpy as np

In [121]:
a = torch.tensor([1, 2, 3])
a

tensor([1, 2, 3])

In [122]:
b = a.numpy()
b

array([1, 2, 3])

In [123]:
type(b)

numpy.ndarray

In [124]:
c = np.array([1, 2, 3])
c

array([1, 2, 3])

In [125]:
torch.from_numpy(c)

tensor([1, 2, 3])